### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by vikasraj00**

### CODE REVIEW

**Comment by Wessel** [comment]
The reason why its `customising` and not `customizing` is because Derpy is brittish and he wants it his way, Derpy himself can look if he wants to accept this change 😔

**Comment by ohlookitsderpy** [comment]
The decision to use ``customising`` was intentional, therefore I am closing this pull request. At some point in the future when language support on the site is implemented I will create an ``English (US)`` locale.

**Comment by vikasraj00** [comment]
> The decision to use `customising` was intentional, therefore I am closing this pull request. At some point in the future when language support on the site is implemented I will create an `English (US)` locale.

sure

**Comment by vikasraj00** [comment]
> The reason why its `customising` and not `customizing` is because Derpy is brittish and he wants it his way, Derpy himself can look if he wants to accept this change 😔

My Bad

**Pull request closed without merging**
